name: Build Windows

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build
        run: .\gradlew.bat installDist

      - name: Package with jpackage
        run: >
          jpackage
          --type app-image
          --input app\build\install\app\lib
          --main-jar app.jar
          --main-class org.example.App
          --name WarhammerVTT
          --dest output

      - uses: actions/upload-artifact@v4
        with:
          name: WarhammerVTT-windows
          path: output\WarhammerVTT\
